### ISSUE TITLE
pdf printing

### ISSUE THREAD

**Issue by robertconnect** [turbo-bert/dcx#2]
`opts.set_preference("print.always_print_silent", True)
opts.set_preference("print.printer_Mozilla_Save_to_PDF.print_paper_id", "iso_a4")
opts.set_preference("print.printer_Mozilla_Save_to_PDF.print_paper_height", "297.000")
opts.set_preference("print.printer_Mozilla_Save_to_PDF.print_paper_width", "210.000")
opts.set_preference("print.printer_Mozilla_Save_to_PDF.print_to_file", True)
opts.set_preference("print.printer_Mozilla_Save_to_PDF.print_paper_size_unit", 1)
opts.set_preference("print.printer_Mozilla_Save_to_PDF.print_edge_bottom", 10)
opts.set_preference("print.printer_Mozilla_Save_to_PDF.print_edge_top", 10)
opts.set_preference("print.printer_Mozilla_Save_to_PDF.print_edge_left", 10)
opts.set_preference("print.printer_Mozilla_Save_to_PDF.print_edge_right", 10)
opts.set_preference("print.printer_Mozilla_Save_to_PDF.print_to_filename", "print.pdf")
opts.set_preference("print_printer", "Mozilla Save to PDF")
`

**Comment by turbo-bert** [comment]
added for firefox
